FROM tbcp/python:centos

USER bootcamp

RUN sudo python3 -m pip install --upgrade --user setuptools && \
    sudo python3 -m pip uninstall ansible && \
    sudo python3 -m pip install --user ansible "molecule[ansible,docker,lint]" molecule-hetznercloud

# tbcp/ansible:centos
