FROM tbcp/python:debian

USER bootcamp

RUN pip3 install --upgrade --user setuptools

RUN pip3 uninstall ansible 2&> /dev/null

RUN pip3 install --user ansible && \
    pip3 install --user "molecule[ansible,docker,lint]" && \
    pip3 install --user molecule-hetznercloud

# tbcp/ansible:debian
